### ISSUE TITLE
variable names starting with "i" are no good

### ISSUE THREAD

**Issue by x3nb63** [mikebaldry/math_engine#7]
watch this:
<pre>
irb(main):028:0> engine = MathEngine.new
=> #<MathEngine:0x00000005a590d8 @opts={:evaluator=>:calculate, :case_sensitive=>true, :context=>#<MathEngine::Context:0x00000005a59038 @opts={:case_sensitive=>true, :evaluator=>:calculate}, @variables={}, @dynamic_library=#<#<Class:0x00000005a58f98>:0x00000005a58f48>, @libraries=[#<#<Class:0x00000005a58f98>:0x00000005a58f48>, Math]>}>

irb(main):030:0> engine.evaluate("images = 4")
MathEngine::ParseError: Unexpected assignment(=), expected: end
        from /home/ste/.gem/ruby/gems/math_engine-0.6.4/lib/parser.rb:125:in `expect_current'
        from /home/ste/.gem/ruby/gems/math_engine-0.6.4/lib/parser.rb:34:in `statement'
        from /home/ste/.gem/ruby/gems/math_engine-0.6.4/lib/parser.rb:17:in `parse'
        from /home/ste/.gem/ruby/gems/math_engine-0.6.4/lib/math_engine.rb:23:in `evaluate'
        from (irb):30
        from /home/ste/.gem/ruby/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
        from /home/ste/.gem/ruby/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
        from /home/ste/.gem/ruby/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /home/ste/.gem/ruby/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /home/ste/.gem/ruby/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'

irb(main):031:0> engine.evaluate("mages = 4")
=> #<BigDecimal:5a8ca50,'0.4E1',9(18)>
irb(main):032:0>
</pre>

I do not understand why this happens.

**Comment by mikebaldry** [comment]
Hi @x3nb63. This gem is really old, and hasn't been updated in a long time, but feel free to use it. I've just looked at the source code and it looks like the regular expression that matches numbers is consuming `i` as an imaginary, due to #3. I think swapping the order of the number and identifier tokens in the lexer.rb if you wish to make a PR. 

Cheers

**Comment by x3nb63** [comment]
Hi,

I dont mind its age. It works nice for me and its light.

ok, thanks. I'll try.

**Comment by mikebaldry** [comment]
Fixed in b2f0be3
